name: Deploy to Firebase
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install -g firebase-tools
      - run: firebase deploy --only hosting --project motoalgarrobo --token "${{ secrets.FIREBASE_TOKEN }}"
